name: Crashpad Precompile
on: [push, pull_request]
jobs: 
    linux:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, windows-latest]
      steps:
        - name: Install Dependencies (Linux)
          if: runner.os == 'Linux'
          run: sudo apt update -y && sudo apt install -y build-essential zlib1g-dev libcurl4-openssl-dev jq

        - name: Checkout depot_tools
          run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth=1

        - name: Add depot_tools to PATH (Linux)
          if: runner.os == 'Linux'
          run: echo "$(pwd)/depot_tools" >> $GITHUB_PATH

        - name: Add depot_tools to PATH (Windows)
          if: runner.os == 'Windows'
          run: echo "${{github.workspace}}/depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        - name: Checkout Source
          uses: actions/checkout@v4
          with:
            path: 'precompile'

        - name: Copy .gclient file
          run: cp precompile/gclient .gclient

        - name: Checkout Crashpad
          run: gclient sync

        - name: Generate build files
          if: runner.os == 'Linux'
          working-directory: crashpad
          run: gn gen out/Default --args='target_cpu="x64" clang_path="//third_party/linux/clang/linux-amd64" target_sysroot="//third_party/linux/sysroot" is_debug=false'

        - name: Set up GN arguments
          if: runner.os == 'Windows'
          run: echo "GN_ARGS=target_cpu='\"x64\"' is_debug=false" >> $GITHUB_ENV

        - name: Generate build files
          if: runner.os == 'Windows'
          working-directory: crashpad
          run: gn gen out/Default --args="${{ env.GN_ARGS }}"

        - name: Build Crashpad
          working-directory: crashpad
          run: ninja -C out/Default crashpad_handler
