
name: Crashpad Precompile
on: [push, pull_request]
jobs: 
    compile-unix:
      name: ${{ matrix.cfg.name }} ${{ matrix.cfg.target_cpu }}
      runs-on: ${{ matrix.cfg.os }}
      strategy:
        fail-fast: false
        matrix:
          cfg:
            - { os: ubuntu-latest, name: "Linux", target_cpu: "x64",   artifact: "lib/linux/amd64", upload_include: True}
            - { os: macos-latest,  name: "macOS", target_cpu: "x64",   artifact: "lib/macos/amd64", upload_include: False}
            - { os: macos-latest,  name: "macOS", target_cpu: "arm64", artifact: "lib/macos/arm64", upload_include: False}
      steps:
        - name: Install Dependencies (Linux)
          if: runner.os == 'Linux'
          run: sudo apt update -y && sudo apt install -y build-essential zlib1g-dev libcurl4-openssl-dev

        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
 
        - name: Checkout depot_tools
          run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth=1

        - name: Add depot_tools to PATH
          run: echo "$(pwd)/depot_tools" >> $GITHUB_PATH

        - name: Checkout Source
          uses: actions/checkout@v4
          with:
            path: 'precompile'

        - name: Copy .gclient file
          run: cp precompile/.ci/gclient .gclient

        - name: Checkout Crashpad
          run: gclient sync

        - name: Generate build files (Linux)
          if: runner.os == 'Linux'
          working-directory: crashpad
          run: gn gen out/Default --args='target_cpu="${{ matrix.cfg.target_cpu }}" clang_path="//third_party/linux/clang/linux-amd64" target_sysroot="//third_party/linux/sysroot" is_debug=false'

        - name: Generate build files (macOS)
          working-directory: crashpad
          if: runner.os == 'macOS'
          run: gn gen out/Default --args='target_cpu="${{ matrix.cfg.target_cpu }}" is_debug=false'

        - name: Build Crashpad
          working-directory: crashpad
          run: ninja -C out/Default crashpad_handler

        - name: Prepare artifact directory (all)
          run: |
            # Create directories
            mkdir -p /tmp/crashpad/${{ matrix.cfg.artifact }}
            mkdir -p /tmp/crashpad/bin/${{ matrix.cfg.name }}.${{ matrix.cfg.target_cpu }}

            # Copy crashpad_handler and set permissions
            cp crashpad/out/Default/crashpad_handler /tmp/crashpad/bin/${{ matrix.cfg.name }}.${{ matrix.cfg.target_cpu }}
            chmod +x /tmp/crashpad/bin/${{ matrix.cfg.name }}.${{ matrix.cfg.target_cpu }}/crashpad_handler

            # Copy lib objects
            cp crashpad/out/Default/obj/client/libclient.a /tmp/crashpad/${{ matrix.cfg.artifact }}/libclient.a
            cp crashpad/out/Default/obj/client/libcommon.a /tmp/crashpad/${{ matrix.cfg.artifact }}/libcommon.a
            cp crashpad/out/Default/obj/util/libutil.a /tmp/crashpad/${{ matrix.cfg.artifact }}/libutil.a
            cp crashpad/out/Default/obj/third_party/mini_chromium/mini_chromium/base/libbase.a /tmp/crashpad/${{ matrix.cfg.artifact }}/libbase.a

        - name: Prepare artifact directory (mac)
          if: runner.os == 'macOS'
          run: |
            cp crashpad/out/Default/obj/BUILD_DIR/gen/util/mach/mig_output.child_portServer.o /tmp/crashpad/${{ matrix.cfg.artifact }}/mig_output.child_portServer.o
            cp crashpad/out/Default/obj/BUILD_DIR/gen/util/mach/mig_output.child_portUser.o /tmp/crashpad/${{ matrix.cfg.artifact }}/mig_output.child_portUser.o
            cp crashpad/out/Default/obj/BUILD_DIR/gen/util/mach/mig_output.notifyUser.o /tmp/crashpad/${{ matrix.cfg.artifact }}/mig_output.excServer.o
            cp crashpad/out/Default/obj/BUILD_DIR/gen/util/mach/mig_output.excServer.o /tmp/crashpad/${{ matrix.cfg.artifact }}/mig_output.excUser.o
            cp crashpad/out/Default/obj/BUILD_DIR/gen/util/mach/mig_output.excUser.o /tmp/crashpad/${{ matrix.cfg.artifact }}/mig_output.mach_excServer.o
            cp crashpad/out/Default/obj/BUILD_DIR/gen/util/mach/mig_output.notifyServer.o /tmp/crashpad/${{ matrix.cfg.artifact }}/mig_output.mach_excUser.o
            cp crashpad/out/Default/obj/BUILD_DIR/gen/util/mach/mig_output.mach_excUser.o /tmp/crashpad/${{ matrix.cfg.artifact }}/mig_output.notifyServer.o
            cp crashpad/out/Default/obj/BUILD_DIR/gen/util/mach/mig_output.mach_excServer.o /tmp/crashpad/${{ matrix.cfg.artifact }}/mig_output.notifyUser.o

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: crashpad-${{ matrix.cfg.name }}-${{ matrix.cfg.target_cpu }}
            path: /tmp/crashpad
            compression-level: 0 # No compression

        - name: Upload build header files
          if: ${{ matrix.cfg.upload_include }}
          uses: actions/upload-artifact@v4
          with:
            name: crashpad-unix-header
            path: ${{github.workspace}}/crashpad/out/Default/gen/build/chromeos_buildflags.h
            if-no-files-found: error

    compile-windows:
      name: Windows ${{ matrix.cfg.arch }}
      runs-on: ${{ matrix.cfg.os }}
      strategy:
        fail-fast: false
        matrix:
          cfg:
            # arch is for ilammy/msvc-dev-cmd, because it won't accept i386 as input, and target_cpu is for gn
            - { os: windows-latest, arch: "x86", artifact: "lib/windows/i386"}
            - { os: windows-latest, arch: "x64", artifact: "lib/windows/amd64"}
      steps:
        - name: Checkout depot_tools
          run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth=1

        - name: Add depot_tools to PATH
          run: echo "${{github.workspace}}/depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        - name: Checkout Source
          uses: actions/checkout@v4
          with:
            path: 'precompile'

        - name: Copy .gclient file
          run: cp precompile/.ci/gclient .gclient

        - name: Configure MSBuild
          uses: ilammy/msvc-dev-cmd@v1
          with:
            arch: ${{ matrix.cfg.arch }}

        - name: Checkout Crashpad
          run: gclient sync

        - name: Generate build files
          working-directory: crashpad
          run: gn gen out/Default --args='target_cpu=\"${{ matrix.cfg.arch }}\"'

        - name: Build Crashpad
          working-directory: crashpad
          run: ninja -C out/Default crashpad_handler

        - name: Prepare artifact directory (all)
          run: |
            # Create directories
            New-Item -ItemType Directory -Force -Path "${{github.workspace}}\gha-dist\${{ matrix.cfg.artifact }}"
            New-Item -ItemType Directory -Force -Path "${{github.workspace}}\gha-dist\bin\${{ matrix.cfg.name }}.${{ matrix.cfg.target_cpu }}"

            # Copy crashpad_handler
            Copy-Item -Path "${{github.workspace}}\crashpad\out\Default\crashpad_handler.exe" -Destination "${{github.workspace}}\gha-dist\bin\${{ matrix.cfg.name }}.${{ matrix.cfg.target_cpu }}"

            # Copy lib objects
            Copy-Item -Path "${{github.workspace}}\crashpad\out\Default\obj\client\client.lib" -Destination "${{github.workspace}}\gha-dist\${{ matrix.cfg.artifact }}\client.lib"
            Copy-Item -Path "${{github.workspace}}\crashpad\out\Default\obj\client\common.lib" -Destination "${{github.workspace}}\gha-dist\${{ matrix.cfg.artifact }}\common.lib"
            Copy-Item -Path "${{github.workspace}}\crashpad\out\Default\obj\util\util.lib" -Destination "${{github.workspace}}\gha-dist\${{ matrix.cfg.artifact }}\util.lib"
            Copy-Item -Path "${{github.workspace}}\crashpad\out\Default\obj\third_party\mini_chromium\mini_chromium\base\base.lib" -Destination "${{github.workspace}}\gha-dist\${{ matrix.cfg.artifact }}\base.lib"

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: crashpad-windows-${{ matrix.cfg.arch }}
            path: ${{github.workspace}}\gha-dist

    generate-dist:
      name: Combine and Distribute
      runs-on: ubuntu-latest
      needs: [compile-unix, compile-windows]
      steps:
        - name: Checkout Source
          uses: actions/checkout@v4
          with:
            path: 'precompile'

        - run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth=1
        - run: echo "$(pwd)/depot_tools" >> $GITHUB_PATH
        - run: cp precompile/.ci/gclient .gclient
        - run: gclient sync --deps=mac,linux,win

        - name: Download precompiled artifacts
          uses: actions/download-artifact@v4
          with:
            path: ${{github.workspace}}/precompile/packer/artifacts
            merge-multiple: true

        - name: Download linux header artifact
          uses: actions/download-artifact@v4
          with:
            name: crashpad-unix-header
            path: /tmp/crashpad/generated-headers-dir/build

        - run: tree /tmp/crashpad/generated-headers-dir

        - name: Set environment variables (DIST_TYPE, CRASHPAD_HASH)
          run: |
            echo "CRASHPAD_HASH=$(git -C crashpad rev-parse --short HEAD)" >> $GITHUB_ENV
            echo "DIST_TYPE=universal" >> $GITHUB_ENV

        - name: Set environment variables (OUTPUT_FILE_NAME)
          run: echo "OUTPUT_FILE_NAME=crashpad-precompiled-${{env.CRASHPAD_HASH}}-${{env.DIST_TYPE}}" >> $GITHUB_ENV  

        - name: Package artifacts and prepare for artifact upload
          working-directory: ${{github.workspace}}/precompile/packer
          env:
            CRASHPAD_SOURCE_DIR: ${{github.workspace}}/crashpad
            MINI_CHROMIUM_SOURCE_DIR: ${{github.workspace}}/crashpad/third_party/mini_chromium/mini_chromium
            GENERATED_HEADERS_DIR: /tmp/crashpad/generated-headers-dir
          run: |
            mkdir build
            cd build && cmake ..
            cpack
            unzip ${{env.OUTPUT_FILE_NAME}}.zip -d extracted

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: crashpad-precompiled
            path: ${{github.workspace}}/precompile/packer/build/extracted

    unix-test:
      name: Test Distribution - ${{ matrix.cfg.name }} ${{ matrix.cfg.target_cpu }}
      runs-on: ${{ matrix.cfg.os }}
      needs: [generate-dist]
      strategy:
        fail-fast: false
        matrix:
          cfg:
            - { os: ubuntu-latest, name: "Linux", arch: "x64"}
            - { os: macos-latest,  name: "macOS", arch: "x64"}
      steps:
        - name: Install Dependencies (Linux)
          if: runner.os == 'Linux'
          run: sudo apt update -y && sudo apt install -y tree clang

        - name: Checkout Source
          uses: actions/checkout@v4
          with:
            path: 'precompile'

        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            pattern: crashpad-precompiled
            path: ${{github.workspace}}/precompile/test/libs/crashpad
            merge-multiple: true

        - run: tree ${{github.workspace}}/precompile/test/
          if: runner.os == 'Linux'

        - name: Build Test Project
          working-directory: ${{github.workspace}}/precompile/test
          run: |
              mkdir -p build
              cd build && cmake ..
              make
    
    windows-test:
      needs: [generate-dist]
      name: Test Distribution - Windows ${{ matrix.arch }}
      strategy:
        fail-fast: false
        matrix:
          arch: [x86, x64]
      runs-on: windows-2019
      steps:
        - name: Checkout Source
          uses: actions/checkout@v4
          with:
            path: precompile

        - name: Install chocolatey packages (i386)
          if: ${{ matrix.arch == 'x86' }}
          run: choco install ninja -y --x86

        - name: Install chocolatey packages (x64)
          if: ${{ matrix.arch == 'x64' }}
          run: choco install ninja -y

        - name: Configure MSBuild
          uses: ilammy/msvc-dev-cmd@v1
          with:
            arch: ${{ matrix.arch }}

        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            pattern: crashpad-precompiled
            path: ${{github.workspace}}/precompile/test/libs/crashpad
            merge-multiple: true

        - name: Generate CMake
          working-directory: precompile/test
          run: mkdir -p build && cd build && cmake -G Ninja ..

        - name: Build Project
          run: cmake --build precompile/test/build
