
name: Crashpad Precompile
on: [push, pull_request]
jobs: 
    linux:
      name: ${{ matrix.cfg.name }}
      runs-on: ${{ matrix.cfg.os }}
      strategy:
        fail-fast: false
        matrix:
          cfg:
            - { os: ubuntu-latest, name: "Linux x64" }
            - { os: macos-latest, name: "macOS x64" }
      steps:
        - name: Install Dependencies (Linux)
          if: runner.os == 'Linux'
          run: sudo apt update -y && sudo apt install -y build-essential zlib1g-dev libcurl4-openssl-dev jq

        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
 
        - name: Checkout depot_tools
          run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth=1

        - name: Add depot_tools to PATH
          run: echo "$(pwd)/depot_tools" >> $GITHUB_PATH

        - name: Checkout Source
          uses: actions/checkout@v4
          with:
            path: 'precompile'

        - name: Copy .gclient file
          run: cp precompile/gclient .gclient

        - name: Checkout Crashpad
          run: gclient sync

        - name: Generate build files (Linux)
          if: runner.os == 'Linux'
          working-directory: crashpad
          run: gn gen out/Default --args='target_cpu="x64" clang_path="//third_party/linux/clang/linux-amd64" target_sysroot="//third_party/linux/sysroot" is_debug=false'

        - name: Generate build files (macOS)
          working-directory: crashpad
          if: runner.os == 'macOS'
          run: gn gen out/Default --args='target_cpu="x64" is_debug=false'

        - name: Build Crashpad
          working-directory: crashpad
          run: ninja -C out/Default crashpad_handler
    
    windows-x64:
      name: Windows x64
      runs-on: windows-latest
      steps:
        - name: Checkout depot_tools
          run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth=1

        - name: Add depot_tools to PATH
          run: echo "${{github.workspace}}/depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        - name: Checkout Source
          uses: actions/checkout@v4
          with:
            path: 'precompile'

        - name: Copy .gclient file
          run: cp precompile/gclient .gclient

        - name: Checkout Crashpad
          run: gclient sync

        - name: Generate build files
          working-directory: crashpad
          run: gn gen out/Default --args='target_cpu=\"x64\"'

        - name: Build Crashpad
          working-directory: crashpad
          run: ninja -C out/Default crashpad_handler